import os
os.system('pip install tk-tools')
os.system('pip install opencv-contrib-python')
os.system('pip install opencv-python')
os.system('pip install datetime')
os.system('pip install pytest-shutil')
os.system('pip install numpy')
os.system('pip install pillow ')
os.system('pip install pandas')
os.system('pip install time')
os.system('pip install python-csv')
os.system('pip install cmake')
os.system('pip install dlib')
os.system('pip install face_recognition')